### ISSUE TITLE
Some weeks are not downloading

### ISSUE THREAD

**Issue by aidank** [dgorissen/coursera-dl#49]
I've been using coursera-dl on Ubuntu successfully for several months, but recently I've encountered an issue where only the first weeks of a completed course will download. For example, "A Beginner's Guide to Irrational Behaviour" (behavioralecon-001) has 6 weeks of videos but only the first and some of the second week download. No error message is produced as far as I can make out. I've also encountered the same issue with linearopt-001.

**Comment by olegafx** [comment]
Works well for me (A Beginner's Guide to Irrational Behaviour)

**Comment by dgorissen** [comment]
mmm Im on a mobile connection so cant test now. Which parser are you using and does using a differnet parser (e.g., html5lib) fix anything?

**Comment by altimerk** [comment]
Hi, I got the same issue. When I tried to download compfinance-003 course, it grabbed only first two week's  lectures. I found, that issue is soup 
soup = BeautifulSoup(vidpage,self.parser)
gets incomplete html content though it contains all closing tags such as 'body', 'html', and so on. 
In other courses, for example progfun-002,  soap gets content which contains 'li' tags without any included div tags, and we get issue similar #18.

**Comment by dgorissen** [comment]
Can you confirm that this also happens with a different parser, e.g., try both html5lib and lxml.

**Comment by altimerk** [comment]
Hi, i've got that issue with lxml, because it's default parser in 1.4.8 version. When I changed to html.parser it was ok!
When I use html5lib I get message:
- Collecting downloadable content from https://class.coursera.org/progfun-002/lecture/index
  Warning: no downloadable content found for progfun-002, did you accept the honour code?

**Comment by aidank** [comment]
I see the same behaviour on my machine as reported by altimerk above: using the defaukt (lxml) the download stops prematurely with some weeks missing; using html5lib nothing downloads and a warning is produced ("Warning: no downloadable content found for behavioralecon-001, did you accept the honour code?"); using html.parser appears to solve the problem and everything downloads successfully.

Many thanks for helping to resolve this!

**Comment by dgorissen** [comment]
Good thats resolved. In light of all this it probably makes sense to use html.parser as the default.
